[supervisord]
nodaemon=true
logfile=/tmp/supervisord.log
pidfile=/tmp/supervisord.pid

[program:flask]
command=gunicorn app:app --bind 127.0.0.1:5000 --workers 1 --timeout 120
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:n8n]
command=n8n start
environment=N8N_PATH="/n8n/",WEBHOOK_URL="https://shenzen12-saba-n8n.hf.space/",N8N_EDITOR_BASE_URL="https://shenzen12-saba-n8n.hf.space/n8n/"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:nginx]
command=nginx -c /app/nginx.conf -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
